#!/usr/bin/env python3
# -*- coding: utf-8 -*-

class BasicLabels:

	AVAILABLE_MODULES = 'Available modules:'
	NOT_ADMIN = 'No Admin Privileges'
	FATAL_ERROR = 'Fatal error'
	NOT_ADMIN = 'No Admin Privileges'
	MODULE_ERROR = 'Unable to load any module'
	ERROR = 'Error'
	HELP = 'Help'
	JOBS = 'Jobs'
	ADD_JOB = 'Add job'
	TIP_ADD_JOB = 'Add job as configured above to job queue'
	SELECT = 'Select'
	QUIT = 'Quit'
	ARE_YOU_SURE = 'Are you sure?'
	REMOVE_LAST = 'Remove last'
	TIP_REMOVE_LAST_JOB = 'Remove last job from the job queue'
	INFOS = 'Infos'
	CLEAR_INFOS = 'Clear infos'
	START_JOBS = 'Start jobs'
	TIP_START_JOBS = 'Start job after job in queue'
	RUNNING = 'Running'
	NOTHING2DO = 'Add jobs! Nothing to do here.'
	ALL_DONE = 'All done.'
	FINISHED_ALL_JOBS = 'Finished all jobs.'
	EXCEPTIONS = 'Exceptions occured!'
	UNDETECTED = 'Could not detect what to do!'
	DESTINATION = 'Destination'
	DIRECTORY = 'Directory'
	SELECT_OUTDIR = 'Select destination directory'
	TIP_OUTDIR = '''Select destination directory to write
logs and resulting file(s)'''
	OUTDIR_REQUIRED = 'Destination directory is required'
	FILENAME = 'Filename'
	TIP_FILENAME = '''Base of filename for generated files,
klick to auto generate from actual time
(when empty)'''
	SELECT_FILE = 'Select file'
	TASK = 'Task'
	TIP_RADIO_BUTTONS = 'Select one option'
	SELECT_SOURCE = 'Select Source'
	TIP_SOURCE = 'Select source = root directory'
	SOURCE_REQUIRED = 'Source is required'
	MISSING_ENTRY = 'Missing entry'
	TSV_FILE = 'TSV file'
	COLUMN = 'Column'
	TSV_NO_HEAD = 'TSV file has no head line'
	TIP_TSV_NO_HEAD = '''Select if given TSV file
has no head line'''
	SELECT_COLUMN = 'Select column'
	FIRST_CHOOSE_TSV = 'First choose text/TSV file to select a column'

class AxCheckerLabels(BasicLabels):

	CASE_FILE = 'Case File'
	OPEN_CASE_FILE = 'Open case file'
	TIP_CASE_FILE = 'Select Case.mfdb in the AXIOM case directory'
	ROOT = 'Root ID '
	TIP_ROOT = '''Select Source ID of the root structure,
required when task is to compare to a
file structure or a TSV list of file paths'''
	CHECK = 'List files that are not represented in hits/artifacts'
	SELECT_COMP_DIR = 'Select directory to compare content'
	TIP_COMP_DIR = '''Compare filepaths under given directory to
files under given root (by ID) in AXIOM case'''
	TIP_COMP_TSV = '''Compate filepaths in given TSV file to
files under given root (by ID) in AXIOM case'''
	TIP_TSV_COLUMN = '''Select column in TSV file containing
the relative file paths to compare'''
	FIRST_CHOOSE_CASE = 'First choose AXIOM case file (Case.mfdb)'
	SELECT_ROOT = 'Select source root (e.g. partition or directory)'
	CASE_REQUIRED = 'AXIOM case file is required'
	ROOT_ID_REQUIRED = 'AXIOM source ID of root to compare is required'
	ROOT_DIR_REQUIRED = 'Root directory (or drive) to compare with AXIOM case is required'
	TSV_AND_COL_REQUIRED = 'Text/TSV file and column matching the AXIOM partition are required'

'''
	SOURCE = 'Source'
	ASK_SOURCE = 'Select source'
	PATH = 'Path'
	DIRECTORY = 'Directory'
	
	FILENAME = 'Filename'
	OUTDIR = 'Outdir'
	SELECT_DEST_DIR = 'Select destination directory'
	FILTER = 'Filter'
	FLAT = 'Flat structure without folders'
	ISO_IMAGE = 'ISO image'
	EWF_IMAGE = 'EWF/E01 image'
	IMAGE = 'Image'
	IMAGE_REQUIRED = 'Image required'
	SELECT_IMAGE = 'Select image file'
	IMAGE_NAME = 'Name'
	IMAGE_DESCRIPTION = 'Description'
	CONFIGURATION = 'Configuration'
	MKISOFS = 'mkisofs'
	SELECT_MKISOFS = 'Select mkisofs executable/binary'
	OSCDIMG_EXE = 'OSCDIMG'
	SELECT_OSCDIMG_EXE = 'Select OSCDIMG executable'
	TO_DO = 'To do'
	ISO_REQUIRED = 'ISO image is required'
	CREATE_AND_VERIFY = 'Create and verify image'
	VERIFY_FILE = 'Verify'
	SELECT_VERIFY_FILE = 'Select image file to verify'
	FILEFILTER = 'Filter by file list'
	NO_FILTER = 'No filter'
	NO_FILEFILTER = 'Do not filter by TSV/file list'
	SKIP_PATH_CHECK = 'Skip check of paths by blacklist or whitelist'
	REGEXFILTER = 'RegEx filter'
	CHECK_ALL_PATHS = 'Check if all source paths are in image'
	NO_REGEXFILTER = 'Do not filter by regular expression(s)'
	BLACKLIST = 'Blacklist'
	SELECT_BLACKLIST = 'Select blacklist'
	WHITELIST = 'Whitelist'
	SELECT_WHITELIST = 'Select whitelist'
	COPY_EXE = 'Copy WimMount.exe to destination directory'

	MISSING_ENTRIES = 'Missing entries'
	WRONG_ENTRY = 'Wrong entry'
	SOURCE_REQUIRED = 'Source is required'
	DEST_DIR_REQUIRED = 'Destination directory is required'
	DEST_FN_REQUIRED = 'Destination filename is required'
	IMAGE_REQUIRED = 'Image file is required'
	COMPRESSION = 'Compression'
	MAX = 'Max'
	FAST = 'Fast'
	NONE = 'None'

	WIPE = 'Wipe'
	TARGET = 'Target'
	SELECT_DRIVE = 'Select drive'
	SELECT_FILES = 'Select file(s) to wipe'
	MOUNTPOINT = 'Mointpoint'
	SELECT_MOUNTPOINT = 'Select Directory to mount new partition'
	LOGGING = 'Logging'
	NORMAL_WIPE = 'Normal wipe'
	ALL_BYTES = 'Wipe all bytes/blocks'
	EXTRA_PASS = 'Extra/2 pass wipe'
	VERIFY = 'Verify'
	BLOCKSIZE = 'Block size'
	VALUE = 'Byte to overwrite'
	MAXBADBLOCKS = 'Max. bad blocks'
	MAXRETRIES = 'Max. retries'
	LOG_HEAD = 'Head of log file'
	SELECT_TEXT_FILE = 'Select text file'
	EXE = 'Executable'
	SELECT_EXE = 'Select executable'
	FILE_SYSTEM = 'File system'
	DO_NOT_CREATE = 'Do not create'
	PARTITION_TABLE = 'Partition table'
	VOLUME_NAME = 'Volume name'
	DEFAULT_VOLUME_NAME = 'Volume'
	DRIVE_LETTER = 'Drive letter'
	FILE = 'file'
	FILES = 'files'
	NEXT_AVAILABLE = 'Next available'
	NEED_HEX = 'Byte to overwrite with has to be a hex value'
	BYTE_RANGE = 'Byte to overwrite has to be inbetween 00 and ff'
	NEED_INT = 'An integer value is needed for '
	REFRESH = 'Refresh'
	TARGET_REQUIRED = 'Physical drive or file(s) to wipe required'
	LOGDIR_REQUIRED = 'Target directory for logging required'
	DRIVE_LETTER_IN_USE = 'Drive letter is in use'
	USE_IT_ANYWAY = 'Use it anyway?'
	DATABASE = 'Database'
	SQLITE_DB = 'SQLite DB'
	SELECT_DB = 'Select DB'
	DUMP = 'Dump'
	SCHEMA = 'Schema'
	EXECUTE_SQL = 'Execute SQL'
	ALTERNATIVE = 'Alternative'
	DUMP_SCHEMA = 'Dump schema'
	DUMP_CONTENT = 'Dump content'
	TABLE = 'Table'
	SQL_FILE = 'SQL file'
	SELECT_SQL_FILE = 'Select SQL file'
	FIRST_CHOOSE_DB = 'First choose SQLite database file (.db)'
	SQLITE_DB_REQUIRED = 'SQLite database file is required'
	SQL_FILE_REQUIRED = 'SQL file is required'
	CASE_NO = 'Case number'
	EVIDENCE_NO = 'Evidence number'
	DEF_EVIDENCE_NO = 'EAV'
	DESCRIPTION = 'Description'
	DEF_DESCRIPTION = 'HD'
	EXAMINER_NAME = 'Examiner name'
	NOTES = 'Notes'
	MEDIA_TYPE = 'Media type'
	MEDIA_FLAG = 'Media flag'
	SEGMENT_SIZE = 'Segment size (MiB)'
	AUTO = 'auto'
	SELECT_SOURCE = 'Select source'
	IMAGE_DETAILS_REQUIRED = 'Image details required'
	SETRO = 'Set target to read only'
	TEMPLATE = 'Template'
	SELECT_TEMPLATE = 'Select template file'
	JSON_FILE = 'JSON file'
	SELECT_JSON = 'Select JSON file'
	PARSE_NOW = 'Parse now'
	PREVIEW = 'Preview'
	WRITE_TO_FILE = 'Write to file'
	PARSER_REPORTED = 'Parser reported'
	ERRORS = 'error(s)'
	ADD_SRC_FILES = 'Add file(s) to source'
	ADD_SRC_DIR = 'Add directory to source'
	UNABLE_ACCESS = 'Unable to access'
	ROOT_HELP = 'Root permission might help'
'''